USE weather_app
GO
CREATE TABLE GeneralRequestResponse
(
    id                           INT
    ,date_stamp                  DATETIME
    ,weather_alerts              VARCHAR(1028)
    ,hourly_summary              VARCHAR(1028)
    ,latitude                    GEOGRAPHY
    ,longitude                   GEOGRAPHY
    ,timezone                    VARCHAR(28)
    ,daily                       VARCHAR(500)
    ,flags                       VARCHAR(500)
    ,alerts                      VARCHAR(500)
    ,offset                      VARCHAR(500)
    ,request_time                DATETIME
    ,summary                     VARCHAR(500)
    ,icon                        VARCHAR(500)
    ,nearestStormDistance        DECIMAL
    ,nearestStormBearing         DECIMAL
    ,precipIntensity             DECIMAL
    ,precipProbability           DECIMAL
    ,temperature                 DECIMAL
    ,apparentTemperature         DECIMAL
    ,dewPoint                    DECIMAL
    ,humidity                    DECIMAL
    ,pressure                    DECIMAL
    ,windSpeed                   DECIMAL
    ,windGust                    DECIMAL
    ,windBearing                 DECIMAL
    ,cloudCover                  DECIMAL
    ,uvIndex                     DECIMAL
    ,visibility                  DECIMAL
    ,ozone                       DECIMAL
    ,summary                     VARCHAR(500)
    ,icon                        VARCHAR(500)
    ,minutely_datetime           DATETIME
    ,summary                     VARCHAR(500)
    ,icon                        VARCHAR(500)
    ,sunriseTime                 VARCHAR(500)
    ,sunsetTime                  VARCHAR(500)
    ,moonPhase                   VARCHAR(500)
    ,precipIntensity             VARCHAR(500)
    ,precipIntensityMax          VARCHAR(500)
    ,precipIntensityMaxTime      VARCHAR(500)
    ,precipProbability           VARCHAR(500)
    ,precipType                  VARCHAR(500)
    ,temperatureHigh             VARCHAR(500)
    ,temperatureHighTime         VARCHAR(500)
    ,temperatureLow              VARCHAR(500)
    ,temperatureLowTime          VARCHAR(500)
    ,apparentTemperatureHigh     VARCHAR(500)
    ,apparentTemperatureHighTime VARCHAR(500)
    ,apparentTemperatureLow      VARCHAR(500)
    ,apparentTemperatureLowTime  VARCHAR(500)
    ,dewPoint                    VARCHAR(500)
    ,humidity                    VARCHAR(500)
    ,pressure                    VARCHAR(500)
    ,windSpeed                   VARCHAR(500)
    ,windGust                    VARCHAR(500)
    ,windGustTime                VARCHAR(500)
    ,windBearing                 VARCHAR(500)
    ,cloudCover                  VARCHAR(500)
    ,uvIndex                     VARCHAR(500)
    ,uvIndexTime                 VARCHAR(500)
    ,visibility                  VARCHAR(500)
    ,ozone                       VARCHAR(500)
    ,temperatureMin              VARCHAR(500)
    ,temperatureMinTime          VARCHAR(500)
    ,temperatureMax              VARCHAR(500)
    ,temperatureMaxTime          VARCHAR(500)
    ,apparentTemperatureMin      VARCHAR(500)
    ,apparentTemperatureMinTime  VARCHAR(500)
    ,apparentTemperatureMax      VARCHAR(500)
    ,apparentTemperatureMaxTime  VARCHAR(500)
    ,alert_title                 VARCHAR(500)
    ,regions                     VARCHAR(500)
    ,severity                    VARCHAR(500)
    ,alert_time                  VARCHAR(500)
)